import { fs, globby } from "zx";

const networkKind = ["evm", "cosmos"];
const envKind = ["mainnet", "testnet"];

type MinimalChainConfig = {
  $schema: string;
} & Record<string, any>;

const TIMER_LABEL = `Finished generating ${
  networkKind.length * envKind.length
} chain files 🎉`;

console.time(TIMER_LABEL);

for (const network of networkKind) {
  for (const env of envKind) {
    const chainConfigFiles = await globby(
      `registry/${env}/${network}/*.chain.json`
    );

    const chains = await Promise.all(
      chainConfigFiles.map((chainConfigFile) =>
        fs
          .readJSON(chainConfigFile)
          .then(({ $schema, ...chain }: MinimalChainConfig) => chain)
      )
    );

    const chainsInputFile = {
      $schema: `../../schemas/${network}-chains.schema.json`,
      name: `${env.toUpperCase()} chain list for ${network.toUpperCase()} [generated by 'scripts/codegen-chains.ts', do not edit manually]`,
      timestamp: new Date().toISOString(),
      chains,
    };

    await fs.writeJson(
      `registry/${env}/${network}/generated.chains.json`,
      chainsInputFile,
      { spaces: 2 }
    );
  }
}

console.timeEnd(TIMER_LABEL);
