#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"


bun run test

bun run scripts/codegen-chains.ts 
# add & commit files to git without triggering husky
git add . 
git commit --amend --no-edit --no-verify
